name: Run Python Script

on: 
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment to run tests against'
        type: choice
        required: true
        default: 'stage'
        options:
          - stage
          - prod

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        pip install requests
        pip install requests python-dotenv
        python -m venv venv

    - name: Run Python script
      run: |
        source venv/bin/activate
        ENV=${{ github.event.inputs.ENV }} python /test/test.py
