name: Run Python Script

on: 
  workflow_dispatch:
  inputs:
      ENV:
        description: 'Environment to run tests against'
        type: choice
        required: true
        default: 'stage'
        options:
          - stage
          - prod

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run Python script
      run: |
        pip install --upgrade pip
        pip install virtualenv
        python -m venv venv
        source venv/bin/activate
        pip install requests
        pip install python-dotenv
        ENV=${{ github.event.inputs.ENV }} python base/test/test.py